site_name: 摸鱼精选
edit_uri: https://github.com/calvingit/reading/docs/
site_author: Zhang Wen
copyright: Copyright &copy; 2021 - 2023 Zhang Wen
repo_url: https://github.com/calvingit/reading

nav:
  - ...

theme:
  language: zh
  name: material
  include_sidebar: false
  highlightjs: true
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
  palette:
    # Palette toggle for automatic mode
    - media: '(prefers-color-scheme)'
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  toc:
    toc_depth: 0 # 0为隐藏目录

plugins:
  - search
  - offline
  - awesome-pages # pip install mkdocs-awesome-pages-plugin

extra:
  social:
    - icon: fontawesome/brands/blogger
      link: https://blog.zhangwen.site
      name: Blog
    - icon: fontawesome/brands/github
      link: https://github.com/calvingit
      name: Github
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/zhangwen_site
      name: Twitter
